### ISSUE TITLE
Re-Quest:   Incorporation of Re-Customization into the Free Customization mod.

### ISSUE THREAD

**Issue by SabinStargem** [CTristan/lobotomy-corporation-mods#15]
I have tried out the Free Customization mod, and it is clean and functional.   There was an older mod that did a similar thing, but that had issues with agents reverting to their original settings on rebooting the game.  Thank you.  :)

That said, there was a sort of companion mod that had similar issues:  Re-Customization.  It allowed the player to customize their characters after creation, which should have been very good.  Unfortunately, it also had reversion issues, and the lob cost clashed with free customization.  In effect, you had to switch mods to use them.

I would like to see a Free Re-Customization mod, that integrates the functionality of these features.   Bonus points if the Agent Termination (deletion) mod's feature also got incorporated.  That one has serious performance issues and breaks lasso-selecting employees.

**Comment by CTristan** [comment]
I really like that idea! It shouldn't be too difficult to re-use the same functionality for re-customization.

I wouldn't be opposed to possibly adding a deletion feature similar to the Employee Termination mod, but I'm curious what the use case is for that. If it's because of the random starter agent, I have another mod I haven't released yet that lets you start a new game with no agents and an extra LOB so you can still hire three agents to start with. Would that work better once that mod is available, or would there still be a need to delete agents later on?

**Comment by SabinStargem** [comment]
I use the Goodbye Annoying Deaths mod, which allows agents to revive at the end of the day - sans their gained XP, new gifts, and pre-CS gear getting erased.  A side effect of their immortality is that they can retain certain gifts from prior days, such as White Night's blessing or Crumbling Armor's recklessness that cannot be disabled.  That last one can be bad, because they can't do Attachment work anymore.

I guess rather than Agent Termination, what I would prefer is an improved Goodbye Death mod?  That, or a Gift Collection mod that allows multiple gifts in a slot, but allows the player to pick one to be mechanically active.

**Comment by CTristan** [comment]
Ah, that makes sense, I didn't think about agents with negative gifts. OK, I'll look into implementing agent deletion after I get re-customization implemented.

**Comment by SabinStargem** [comment]
Here is an image of the Delete Agent interface, if that makes things easier.

![Terminate Agent](https://user-images.githubusercontent.com/38871546/214737597-656cc04c-18dc-496f-b742-568a23ed6f01.jpg)

**Comment by CTristan** [comment]
Re-customization has been added to Free Customization. I will move the Agent Termination request to a separate issue.
