### ISSUE TITLE
Request: Add a notification when an agent receives a gift

### ISSUE THREAD

**Issue by CTristan** [CTristan/lobotomy-corporation-mods#21]
I would like to see a notification in the log when an agent receives a gift after working with an abnormality. Some gifts I will want to give to all of my agents, and while I can watch the portrait to see when they receive it some gifts are hard to distinguish visually or maybe my attention got pulled elsewhere. Also gifts in general feel special enough to want to know when someone got one; weapons and armor have to be purchased so you know when you get them but gifts are invisible unless you happen to notice them in the portrait or gift list for an agent.

**Comment by SabinStargem** [comment]
Yeah, this would be helpful.  I tend to farm Child of the Galaxy for his brooch.   Nothing There also has a discreet cheek gift, it can get buried under visual clutter.
