### ISSUE TITLE
 Feather of Glory and Snow Queen

### ISSUE THREAD

**Issue by bohe2333** [CTristan/lobotomy-corporation-mods#66]
it's just as the title
Btw the title is translated by machine translation，sorry.(if that's difficult to understand :F-01-37 and O-02-101'E.G.O
Please😘

**Comment by CTristan** [comment]
That's an excellent idea, thank you! In the next release I'll add in a check for an agent with Feather of Honor being assigned to work for Snow Queen.

**Comment by bohe2333** [comment]
thx!

**Comment by CTristan** [comment]
Mod has been updated with the new check and released on Nexus Mods. Thank you again for the suggestion!
